#!/usr/bin/env python3
"""Generate command reference documentation from lazyjira --help output.

Usage:
    python scripts/generate_docs.py > docs/commands.md

Runs lazyjira and all subcommands with --help, captures output,
and formats it as Markdown documentation.
"""

import subprocess
import sys

COMMANDS = [
    ([], "lazyjira"),
    (["issues"], "issues"),
    (["issues", "list"], "issues list"),
    (["issues", "create"], "issues create"),
    (["issues", "search"], "issues search"),
    (["issues", "read"], "issues read"),
    (["issues", "update"], "issues update"),
    (["comments"], "comments"),
    (["comments", "create"], "comments create"),
    (["comments", "list"], "comments list"),
    (["move"], "move"),
    (["labels"], "labels"),
    (["projects"], "projects"),
    (["open"], "open"),
    (["link"], "link"),
    (["query"], "query"),
]


def get_help(args: list[str]) -> str:
    """Run lazyjira with --help and capture output."""
    cmd = [sys.executable, "-m", "lazyjira"] + args + ["--help"]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    return result.stdout or result.stderr


def main():
    print("# Command Reference")
    print()
    print("> Auto-generated from `lazyjira --help`. Do not edit manually.")
    print()

    for args, name in COMMANDS:
        help_text = get_help(args)
        if not help_text.strip():
            continue

        level = "##" if not args else "###"
        print(f"{level} `lazyjira {' '.join(args)}`" if args else f"{level} `lazyjira`")
        print()
        print("```")
        print(help_text.rstrip())
        print("```")
        print()

    print("---")
    print()
    print("*Generated by `scripts/generate_docs.py`*")


if __name__ == "__main__":
    main()
